### ISSUE TITLE
Error in solver choice via suggestions

### ISSUE THREAD

**Issue by AnvarAtayev** [microprediction/humpday#15]
In suggestions.py, if `suggest` fails to provide a list of suggestions, one should return
`[(None, None, DEFAULT_OPTIMIZER.__name__)]` 
and not
`[(None, None, DEFAULT_OPTIMIZER)]`
since `DEFAULT_OPTIMIZER` is not of string type, which is the case if suggestions are provided.

![image](https://user-images.githubusercontent.com/70859208/150528866-87dac5dc-6b5c-409b-a26b-cf776c35fe57.png)
![image](https://user-images.githubusercontent.com/70859208/150528832-5e1d99b5-ca49-4411-8be3-1fb90974217a.png)

Otherwise, the program seems to fail.

**Comment by microprediction** [comment]
Whoops. Thanks for that. Fixed it.
