### ISSUE TITLE
scipy errors

### ISSUE THREAD

**Issue by rkern** [microprediction/humpday#3]
https://github.com/microprediction/humpday/blob/21969d33bffdbafc7a399f64e29e8a5e483fc28b/humpday/optimizers/scipycube.py#L28

Currently, you are always running `method='powell'` regardless of which method you've requested. The `options` dict is for arguments specific to the optimization method, typically tolerances. There is no `maxfev` option, only `maxiter`.

The `dogleg` method requires a Jacobian function to be provided; it is not a derivative-free method.

The `SLSQP` method is misspelled as `SLQSP`, here and in `shgocube`.

It will be interesting to see how fixing these affects the ELO ratings.

**Comment by microprediction** [comment]
Fantastic catches. Thanks so much.

**Comment by microprediction** [comment]
And yes, we'll see how the new Elo ratings are looking by hump day.

**Comment by microprediction** [comment]
Pushed those fixes, I think. Thanks again, Robert.
